// svelte/my-awesome-app/src/lib/Stepper.svelte
<script>
  import { createEventDispatcher } from 'svelte'

  const dispatch = createEventDispatcher()

  export let count = 0

  const decrement = () => {
    count--
    dispatch('change', { count })
  }

  const increment = () => {
    count++
    dispatch('change', { count })
  }
</script>

<button data-cy="decrement" on:click="{decrement}">-</button>
<span data-cy="counter">{count}</span>
<button data-cy="increment" on:click="{increment}">+</button>

// vue/my-awesome-app/src/components/Stepper.vue
<template>
  <div>
    <button data-cy="decrement" @click="decrement">-</button>
    <span data-cy="counter">{{ count }}</span>
    <button data-cy="increment" @click="increment">+</button>
  </div>
</template>

<script setup>
  import { ref } from 'vue'
  const props = defineProps(['count'])

  const emit = defineEmits(['change'])

  const count = ref(props.count || 0)

  const increment = () => {
    count.value++
    emit('change', count.value)
  }

  const decrement = () => {
    count.value--
    emit('change', count.value)
  }
</script>
