// angular/my-awesome-app/src/app/stepper/stepper.component.ts
import {
  Component,
  model,
  output,
} from '@angular/core'

@Component({
  selector: 'app-stepper',
  template: `
    <div>
      <button data-cy="decrement" (click)="decrement()">-</button>
      <span data-cy="counter">{{ count() }}</span>
      <button data-cy="increment" (click)="increment()">+</button>
    </div>
  `,
})
export class StepperComponent {
  count = model<number>(0)  
  change = output<number>()
  
  increment(): void {
    this.count.set(this.count() + 1);
    this.change.emit(this.count());
  }

  decrement(): void {
    this.count.set(this.count() - 1);
    this.change.emit(this.count());
  }
}

// vue/my-awesome-app/src/components/Stepper.vue
<template>
  <div>
    <button data-cy="decrement" @click="decrement">-</button>
    <span data-cy="counter">{{ count }}</span>
    <button data-cy="increment" @click="increment">+</button>
  </div>
</template>

<script setup>
  import { ref } from 'vue'
  const props = defineProps(['count'])

  const emit = defineEmits(['change'])

  const count = ref(props.count || 0)

  const increment = () => {
    count.value++
    emit('change', count.value)
  }

  const decrement = () => {
    count.value--
    emit('change', count.value)
  }
</script>
